name: Build PDFs
on:
  push:
    branches: ["master"]
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build PDFs
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - run: mkdir build && mv main.pdf build/
      - name: Upload PDFs
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: Deploy PDFs
        uses: actions/deploy-pages@v4
