name: Build PDFs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - run: mkdir build && mv *.pdf build/.
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
