name: Build PDFs
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build PDFs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - run: mkdir build && mv main.pdf build/
      - name: Upload PDFs
        uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - name: Deploy PDFs
        uses: actions/deploy-pages@v2
